--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/OguzhanUmutlu/MoneyUI
build-by-default: true
branches:
- main
projects:
  MoneyUI:
    path: ""
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^1.0.0
      - src: onebone/EconomyS/EconomyAPI
        version: ^5.7.2
...
